# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-12 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conf_app', '0001_initial'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='users',
            field=models.ManyToManyField(to='conf_app.CustomUser'),
        ),
    ]
