# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-12 03:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chat_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 12, 3, 3, 59, 939778, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
