# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-12 03:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chat_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='created_at',
        ),
    ]
