# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-12 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('U', 'User'), ('C', 'Company')], default='U', max_length=3),
        ),
    ]
