# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf_app', '0002_auto_20160605_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userpic',
            field=models.ImageField(blank=True, null=True, upload_to='userpics/'),
        ),
    ]
