# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-12 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf_app', '0002_auto_20160612_0438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='members',
        ),
        migrations.RemoveField(
            model_name='event',
            name='sponsors',
        ),
        migrations.AddField(
            model_name='event',
            name='member',
            field=models.ManyToManyField(blank=True, related_name='member_set', through='conf_app.Participant', to='conf_app.CustomUser'),
        ),
        migrations.AddField(
            model_name='event',
            name='sponsor',
            field=models.ManyToManyField(blank=True, related_name='sponsor_set', to='conf_app.CustomUser'),
        ),
    ]
