# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf_app', '0003_auto_20160605_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='Admin Adminovich', max_length=80),
            preserve_default=False,
        ),
    ]
