# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-12 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf_app', '0005_remove_event_sponsors'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sponsors',
            field=models.ManyToManyField(blank=True, related_name='sponsors_set', to='conf_app.CustomUser'),
        ),
    ]
